#!/bin/bash
## Description: Run pnpm primsa inside the web container
## Usage: primsa [flags] [args]
## Example: "ddev primsa db push" or "ddev prisma migrate dev"
## ExecRaw: true
## HostWorkingDir: true
pnpx prisma "$@"